package kvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXITUNKNOWN-0]
	_ = x[EXITEXCEPTION-1]
	_ = x[EXITIO-2]
	_ = x[EXITHYPERCALL-3]
	_ = x[EXITDEBUG-4]
	_ = x[EXITHLT-5]
	_ = x[EXITMMIO-6]
	_ = x[EXITIRQWINDOWOPEN-7]
	_ = x[EXITSHUTDOWN-8]
	_ = x[EXITFAILENTRY-9]
	_ = x[EXITINTR-10]
	_ = x[EXITSETTPR-11]
	_ = x[EXITTPRACCESS-12]
	_ = x[EXITS390SIEIC-13]
	_ = x[EXITS390RESET-14]
	_ = x[EXITDCR-15]
	_ = x[EXITNMI-16]
	_ = x[EXITINTERNALERROR-17]
	_ = x[EXITIOIN-0]
	_ = x[EXITIOOUT-1]
}

// This was generated by the stringer program as a const. golangci-lint hated the long line it generated.
// golangci-lint is wrong.
// Nothing I can do.
// const _ExitType_name = "EXITUNKNOWNEXITEXCEPTIONEXITIOEXITHYPERCALLEXITDEBUGEXITHLTEXITMMIOEXITIRQWINDOWOPEN
// EXITSHUTDOWNEXITFAILENTRYEXITINTREXITSETTPREXITTPRACCESSEXITS390SIEICEXITS390RESETEXITDCREXITNMIEXITINTERNALERROR"

func (i ExitType) String() string {
	// golangci-lint does not like code generated by the stringer ...
	// So you will not be able to easily recreate this file, but that's life.
	ExitTypex := [...]uint8{0, 11, 24, 30, 43, 52, 59, 67, 84, 96, 109, 117, 127, 140, 153, 166, 173, 180, 197}

	// This nonsenses brought to you by golangci-lint and its inappropriate line length check.
	ExitTypen := "EXITUNKNOWNEXITEXCEPTIONEXITIOEXITHYPERCALLEXITDEBUGEXITHLTEXITMMIOEXITIRQWINDOWOPEN"
	ExitTypen += "EXITSHUTDOWNEXITFAILENTRYEXITINTREXITSETTPREXITTPRACCESSEXITS390SIEICEXITS390RESET"
	ExitTypen += "EXITDCREXITNMIEXITINTERNALERROR"

	if i >= ExitType(len(ExitTypex)-1) {
		return "ExitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}

	return ExitTypen[ExitTypex[i]:ExitTypex[i+1]]
}
