name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
jobs:
  test:
    runs-on: actuated
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: check env
        run: |
          ls -la /dev/kvm
      - name: install deps
        run: |
          sudo -E env "PATH=$PATH" "GO111MODULE=off" go get golang.org/x/tools/cmd/stringer
          sudo -E env "PATH=$PATH" "GO111MODULE=off" go get github.com/mattn/goveralls
          sudo -E env "PATH=$PATH" "GO111MODULE=off" go get github.com/u-root/u-root
          sudo -E env "PATH=$PATH" make golangci-lint initrd vda.img bzImage
      - name: test
        run: |
          sudo -E env "PATH=$PATH" go mod tidy && git diff --no-patch --exit-code go.sum
          sudo -E env "PATH=$PATH" make gokvm
          sudo -E env "PATH=$PATH" make test
